import Head from "next/head";
import Home1 from "./Home";
// import About from "./About";
// import Contact from "./Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>New Next Project (NNP)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home1 />
      </main>
    </div>
  );
}
