import Head from "next/head";
import Home from "./Home";
export const getStaticProps = async () => {
  const res = await fetch("https://api.punkapi.com/v2/beers");
  const Data = await res.json();
  console.log("data", Data);
  return {
    props: {
      Data:Data
    },
  };
};
export default function Index({ Data }) {
  return (
    <div>
      <Head>
        <title>New Next Project (NNP)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home Data={Data} />
      </main>
    </div>
  );}